/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:93cab9b7-de71-4e06-90b0-9c15ebdcf58b",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_BmGB91P5O",
    "aws_user_pools_web_client_id": "5jhpttrlm5hdb6ghv361nhq3a8",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "arool-20230407125740-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "http://arool-20230407125740-hostingbucket-dev.s3-website.ap-south-1.amazonaws.com"
};


export default awsmobile;
